recipes-robot/system-server: add opentrons-system-server recipe
Opentrons/oe-core pull request #49
Opened 2023-01-18 15:28 UTC by fsinapi

This PR adds the `opentrons-system-server` project to the OT3 image.

Changelog:
- Added a recipe for PyJWT version 2.6.0 (latest) and specified it as preferred, because the default in meta-python is 1.7.1
- Added a recipe for opentrons-system-server with a systemd service to run it as a daemon

Test steps:
- [ ] Confirm build completes
- [ ] Upload built image to an OT-3
- [ ] Confirm that `/opt/opentrons-system-server` exists on the filesystem + it has a 
- [ ] Confirm that `systemctl status opentrons-system-server` shows the system server as running
- [ ] Run Python3 repl in opentrons-system-server and confirm that the PyJWT library exists + you can encode/decode using `HS512`

2023-01-18 16:14 UTC, vegano1 commented on layers/meta-opentrons/recipes-robot/opentrons-system-server/opentrons-system-server.bb
> +                       ${sysconfdir}/release-notes.md \
dont think we need these.

2023-01-19 15:08 UTC, sfoster1 requested changes
Couple small things, see inline comments

2023-01-19 15:08 UTC, sfoster1 commented on layers/meta-opentrons/recipes-robot/opentrons-system-server/files/opentrons-system-server.service
> +Environment=PYTHONPATH=/opt/opentrons-system-server:/usr/lib/python3.8/site-packages\
what's that last backslash for?

2023-01-19 15:08 UTC, sfoster1 commented on layers/meta-opentrons/recipes-robot/opentrons-system-server/files/opentrons-system-server.service
> +Type=simple
imo we should use `notify` and pysystemd `sd_notify` in the app

2023-01-19 17:31 UTC, sfoster1 commented on layers/meta-opentrons/recipes-robot/opentrons-system-server/opentrons-system-server.bb
> +RDEPENDS_${PN} += " python3-pyjwt nginx python-aionotify"
what are we using aionotify for?

2023-01-19 17:37 UTC, fsinapi commented on layers/meta-opentrons/recipes-robot/opentrons-system-server/files/opentrons-system-server.service
> +Environment=PYTHONPATH=/opt/opentrons-system-server:/usr/lib/python3.8/site-packages\
typo

2023-01-19 17:38 UTC, fsinapi commented on layers/meta-opentrons/recipes-robot/opentrons-system-server/opentrons-system-server.bb
> +RDEPENDS_${PN} += " python3-pyjwt nginx python-aionotify"
accidental holdover

2023-01-20 16:39 UTC, sfoster1 approved these changes
Okay, looks good to me!

2023-01-20 17:38 UTC, vegano1 commented
lgtm!

2023-01-20 17:38 UTC, vegano1 approved these changes

2023-01-23 14:30 UTC, fsinapi commented
Tested on robot after updating to `notify`, confirmed that the system-server starts up and notifies systemd that it is running (status is active)

2023-01-23 14:31 UTC, merged