recipes-robot/python3-jupyter: add jupyter-notebook and service to enable jupyter web interface.
Opentrons/oe-core pull request #60
Opened 2023-03-02 16:30 UTC by vegano1

# Overview

This adds the layers and services to enable jupyter-notebook on the Flex.

# Test Plan

- [ ] make sure jupyter-notebook service starts when the system starts up
- [ ] make sure we can import Jupyter from python3 interpreter on the flex
- [ ] make sure the web interface is live when clicking on "Launch Jupyter Notebook" button from the desktop app

2023-03-06 14:20 UTC, sfoster1 requested changes
- We need to set the ot-3 specific environment variables
- Because this is most often used to interact with the protocol-running machinery, we need to make sure that `/opt/opentrons-robot-server` is in the kernel pythonpath
- we need to add `meta-jupyter` to `update.sh`

2023-03-06 14:20 UTC, sfoster1 commented on layers/meta-opentrons/recipes-robot/python3-jupyter/files/jupyter-notebook.service
> +Environment=JUPYTER_RUNTIME_DIR=%t/jupyter JUPYTER_CONFIG_DIR=%S/jupyter/config JUPYTER_DATA_DIR=%S/jupyter/data IPYTHONDIR=%S/ipython JUPYTER_NOTEBOOK_DIR=%S/jupyter/notebooks OT_SMOOTHIE_ID=AMA RUN
we need to update these to be the ot-3 specific ones (see the environment flags set in the robot-server unit) rather than the ot-2 specific ones

2023-03-27 18:50 UTC, sfoster1 approved these changes
Okay, this looks good to me if it works. They don't maintain a dunfell release, huh?

2023-03-27 19:45 UTC, vegano1 commented
> Okay, this looks good to me if it works. They don't maintain a dunfell release, huh?

* Tested on Flex, jupyter notebook service starts up correctly
* The "Launch Jupyter Notebook" button on the Opentrons desktop app opens up the jupyter notebook web interface on `http://<robot-ip>:48888/`
* No, they don't currently have a dunfell release.

2023-03-27 21:21 UTC, merged